#### Data parameters
datapath: mnist_data/images_train
affinity: mnist_data/affinity_mnist.csv
classes: mnist_data/classes_mnist.csv
datatype: npy
limit: 1000
no_val_drop: true
split: 20
date_time_run: mnist-tutorial
new_out: false

#### Data processing parameters
shift_min: false
normalise: false
gaussian_blur: false

#### Network parameters
depth: 4
channels: 8
latent_dims: 16
pose_dims: 1
model: cnn
n_splats: 128
gsd_conv_layers: 0
bnorm_encoder: false
bnorm_decoder: false

#### Training parameters
epochs: 1000
batch: 128
learning: 0.0001
opt_method: adam
classifier: NN
gpu: true
strategy: auto
freq_sta: 10
freq_eval: 10

#### Loss parameters
beta: 0.0001
gamma: 0.001
recon_loss: MSE
klreduction: mean

#### Cyclical annealing parameters for beta
beta_min: 0
beta_cycle: 5
beta_ratio: 0.5
cyc_method_beta: flat

#### Cyclical annealing parameters for gamma
gamma_min: 0
gamma_cycle: 5
gamma_ratio: 0.5
cyc_method_gamma: flat

#### Restart and evaluation parameters
evaluate: false
restart: false

#### Visualization parameters
vis_format: png
tensorboard: false
vis_his: false
vis_aff: false
vis_cyc: false
vis_los: false
vis_acc: false
vis_rec: false
vis_emb: false
vis_dynamic: true
vis_sim: false
vis_int: false
vis_dis: false
vis_pos: false
vis_pose_class: "1,2"
vis_all: true

#### Visualization frequencies
freq_acc: 10
freq_rec: 10
freq_emb: 10
freq_dynamic: 10
freq_sim: 10
freq_int: 10
freq_dis: 10
freq_pos: 10
freq_all: 10

#### Debug parameters
debug: false
